<a href="https://colab.research.google.com/github/kanakesh2006/Practical-Deep-Learning-using-PyTorch/blob/main/Pytorch_NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features
model(features)

tensor([[0.6387],
        [0.6674],
        [0.6846],
        [0.6852],
        [0.6763],
        [0.6663],
        [0.6776],
        [0.6774],
        [0.6759],
        [0.6597]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
print(model.network[0].weight)

Parameter containing:
tensor([[ 0.0087, -0.2822, -0.0250,  0.3591, -0.2294],
        [ 0.2072,  0.0143, -0.3940, -0.1456,  0.2275],
        [-0.4379,  0.1916,  0.3923, -0.1772,  0.3526]], requires_grad=True)


In [4]:
print(model.network[2].weight)

Parameter containing:
tensor([[ 0.4382, -0.0999,  0.1164]], requires_grad=True)


In [5]:
model.state_dict()

OrderedDict([('network.0.weight',
              tensor([[ 0.0087, -0.2822, -0.0250,  0.3591, -0.2294],
                      [ 0.2072,  0.0143, -0.3940, -0.1456,  0.2275],
                      [-0.4379,  0.1916,  0.3923, -0.1772,  0.3526]])),
             ('network.0.bias', tensor([ 0.4134,  0.0364, -0.3339])),
             ('network.2.weight', tensor([[ 0.4382, -0.0999,  0.1164]])),
             ('network.2.bias', tensor([0.5765]))])

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00