<a href="https://colab.research.google.com/github/kanakesh2006/Practical-Deep-Learning-using-PyTorch/blob/main/PyTorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

train test and split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.73849325, -1.10351459, -0.73053639, ..., -0.60054145,
         0.08983598,  0.46665524],
       [-0.12095784, -0.36938818, -0.17141253, ..., -0.34825059,
        -0.59373649, -0.79696215],
       [-1.51083164, -0.80505008, -1.46750792, ..., -0.13014008,
         0.06559582,  1.03016029],
       ...,
       [-0.10698645,  1.10608555, -0.13974103, ..., -0.803631  ,
        -0.35941496, -1.16067905],
       [-0.31655729,  0.38640097, -0.34398162, ..., -0.77450872,
         0.50191867, -1.09579059],
       [-0.38361996, -1.39716515, -0.3935191 , ..., -0.45033183,
        -0.5194    , -0.0609904 ]])

In [10]:
y_train

478    B
483    B
114    B
370    M
264    M
      ..
500    B
202    M
243    B
150    B
312    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,

Numpy array to PyTorch tensors

In [13]:
import torch

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor

tensor([[-0.7385, -1.1035, -0.7305,  ..., -0.6005,  0.0898,  0.4667],
        [-0.1210, -0.3694, -0.1714,  ..., -0.3483, -0.5937, -0.7970],
        [-1.5108, -0.8051, -1.4675,  ..., -0.1301,  0.0656,  1.0302],
        ...,
        [-0.1070,  1.1061, -0.1397,  ..., -0.8036, -0.3594, -1.1607],
        [-0.3166,  0.3864, -0.3440,  ..., -0.7745,  0.5019, -1.0958],
        [-0.3836, -1.3972, -0.3935,  ..., -0.4503, -0.5194, -0.0610]],
       dtype=torch.float64)

In [16]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [17]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred))
    return loss.mean()

important parameters

In [18]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [19]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')



Epoch: 1, Loss: 4.048048008990738
Epoch: 2, Loss: 3.9376492533655725
Epoch: 3, Loss: 3.8221998978386766
Epoch: 4, Loss: 3.701824751320634
Epoch: 5, Loss: 3.5728872714573012
Epoch: 6, Loss: 3.430874799078759
Epoch: 7, Loss: 3.2878863430006127
Epoch: 8, Loss: 3.1417237829863565
Epoch: 9, Loss: 2.9929028508764963
Epoch: 10, Loss: 2.841409659795367
Epoch: 11, Loss: 2.6886387465540578
Epoch: 12, Loss: 2.531402123967564
Epoch: 13, Loss: 2.37588610796706
Epoch: 14, Loss: 2.2176521275386736
Epoch: 15, Loss: 2.061643641058072
Epoch: 16, Loss: 1.908146419396225
Epoch: 17, Loss: 1.7587976045115543
Epoch: 18, Loss: 1.6146400129049547
Epoch: 19, Loss: 1.4786076450995758
Epoch: 20, Loss: 1.3523249853585155
Epoch: 21, Loss: 1.2408082005484953
Epoch: 22, Loss: 1.1453857247993111
Epoch: 23, Loss: 1.0665608041511907
Epoch: 24, Loss: 1.0035835902908747
Epoch: 25, Loss: 0.9545347830517333


In [20]:
model.weights

tensor([[ 0.1540],
        [ 0.4754],
        [-0.3796],
        [ 0.3143],
        [ 0.0423],
        [ 0.2702],
        [-0.6159],
        [ 0.0753],
        [-0.0400],
        [ 0.0829],
        [-0.2768],
        [ 0.6424],
        [ 0.3228],
        [ 0.2949],
        [ 0.0358],
        [-0.0288],
        [-0.0896],
        [-0.1423],
        [ 0.7541],
        [-0.1916],
        [-0.2039],
        [ 0.2859],
        [ 0.3016],
        [-0.3401],
        [-0.0306],
        [ 0.2913],
        [ 0.2653],
        [ 0.2537],
        [-0.1594],
        [ 0.1058]], dtype=torch.float64, requires_grad=True)

In [21]:
model.bias

tensor([-0.1252], dtype=torch.float64, requires_grad=True)

In [22]:
 # model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5046167969703674
