<a href="https://colab.research.google.com/github/kanakesh2006/Practical-Deep-Learning-using-PyTorch/blob/main/PyTorch_Training_Pipeline_using_NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

train test and split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.40081375, -0.74150069, -0.45435679, ..., -0.86254119,
        -0.82051278, -1.08163767],
       [-2.03075086, -1.47392173, -1.98608485, ..., -1.75639881,
         0.03754508,  0.51929154],
       [-1.35168066,  0.50074285, -1.33556916, ..., -1.36676077,
        -0.8314534 ,  0.4244855 ],
       ...,
       [-0.30805996,  0.70658667, -0.22406771, ..., -0.04527389,
         1.90682958,  1.26157971],
       [ 0.8246606 , -0.76304248,  0.95713184, ...,  2.11870647,
         1.80992687,  1.1700057 ],
       [-0.88425776, -1.10771121, -0.85705698, ..., -0.12277599,
         0.61427248,  0.356613  ]])

In [ ]:
y_train

69     B
101    B
412    B
529    B
550    B
      ..
391    B
209    B
208    B
25     M
342    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,

Numpy array to PyTorch tensors

In [ ]:
import torch

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[-0.4008, -0.7415, -0.4544,  ..., -0.8625, -0.8205, -1.0816],
        [-2.0308, -1.4739, -1.9861,  ..., -1.7564,  0.0375,  0.5193],
        [-1.3517,  0.5007, -1.3356,  ..., -1.3668, -0.8315,  0.4245],
        ...,
        [-0.3081,  0.7066, -0.2241,  ..., -0.0453,  1.9068,  1.2616],
        [ 0.8247, -0.7630,  0.9571,  ...,  2.1187,  1.8099,  1.1700],
        [-0.8843, -1.1077, -0.8571,  ..., -0.1228,  0.6143,  0.3566]],
       dtype=torch.float64)

In [ ]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [ ]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out


In [ ]:
loss_function = nn.BCELoss()

In [ ]:
type(loss_function)

torch.nn.modules.loss.BCELoss

important parameters

In [ ]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model(X_train_tensor.float())

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1).float())

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()


    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.4842173457145691
Epoch: 2, Loss: 0.4204205572605133
Epoch: 3, Loss: 0.3774316608905792
Epoch: 4, Loss: 0.34594467282295227
Epoch: 5, Loss: 0.32155805826187134
Epoch: 6, Loss: 0.3019242584705353
Epoch: 7, Loss: 0.2856624722480774
Epoch: 8, Loss: 0.2718985676765442
Epoch: 9, Loss: 0.26004740595817566
Epoch: 10, Loss: 0.24970003962516785
Epoch: 11, Loss: 0.24056100845336914
Epoch: 12, Loss: 0.2324104756116867
Epoch: 13, Loss: 0.225081205368042
Epoch: 14, Loss: 0.21844324469566345
Epoch: 15, Loss: 0.2123940885066986
Epoch: 16, Loss: 0.20685136318206787
Epoch: 17, Loss: 0.20174838602542877
Epoch: 18, Loss: 0.19703014194965363
Epoch: 19, Loss: 0.19265103340148926
Epoch: 20, Loss: 0.1885727196931839
Epoch: 21, Loss: 0.18476295471191406
Epoch: 22, Loss: 0.18119406700134277
Epoch: 23, Loss: 0.17784236371517181
Epoch: 24, Loss: 0.17468731105327606
Epoch: 25, Loss: 0.17171116173267365


In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1401,  0.1009,  0.1606,  0.3756, -0.0699,  0.0790,  0.0143,  0.2886,
          0.1213, -0.0851,  0.1713, -0.0510,  0.2262,  0.1232, -0.1181, -0.1866,
          0.1190,  0.1790, -0.1138,  0.0611,  0.3939,  0.1910,  0.3726,  0.2199,
          0.2941,  0.2642,  0.2006,  0.3196,  0.2255,  0.0663]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.0404], requires_grad=True)

In [ ]:
 # model evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor.float())
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5470914244651794
