<a href="https://colab.research.google.com/github/kanakesh2006/Practical-Deep-Learning-using-PyTorch/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available, using CPU")

GPU is available
Using GPU : Tesla T4


### Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[-1.4995e-26,  4.3872e-41, -1.4995e-26],
        [ 4.3872e-41,  0.0000e+00,  0.0000e+00]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.0376, 0.4248, 0.0015],
        [0.2146, 0.3788, 0.2520]])

In [ ]:
# using manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange -> ", torch.arange(0,10))

# linspace
print("using linspace -> ", torch.linspace(0,10,10))

# eye
print("using eye -> ", torch.eye(5))

# full
print("using full -> ", torch.full((3,3),5))

using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[134469328862640, 134469328862640,               0],
        [              0,               0,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# convert data types
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

#### 1. Scalar Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# add
x + 2

# sub
x - 2

# mul
x * 2

# div
x / 2

# power
x ** 2

# mod
x % 2

# floor div
x // 2

tensor([[0., 0.],
        [0., 0.]])

#### 2. Element Wise Operation

In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print(a)
print(b)

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])
tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])


In [ ]:
# add
a + b

# sub
a - b

# mul
a * b

# div
a / b

# power
a ** b

# mod
a % b

tensor([[0.1048, 0.7565],
        [0.2239, 0.3023]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.8, 2.5, 5.6, 6.3])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 6., 6.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 6., 7.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 5., 6.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=5)

tensor([2.0000, 2.5000, 5.0000, 5.0000])

#### 3. Reduction Operation


In [ ]:
e = torch.randint(size=(2,3), low = 0, high = 10, dtype=float)
e

tensor([[0., 1., 9.],
        [9., 8., 0.]], dtype=torch.float64)

In [ ]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([10., 17.], dtype=torch.float64)

In [ ]:
# mean
torch.mean(e)

# mean along columns
torch.mean(e, dim=0)

# mean along rows
torch.mean(e, dim=1)

tensor([3.3333, 5.6667], dtype=torch.float64)

In [ ]:
# median
torch.median(e)

# median along columns
torch.median(e, dim=0)

# median along rows
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([1., 8.], dtype=torch.float64),
indices=tensor([1, 1]))

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0., dtype=torch.float64)

In [ ]:
# product
torch.prod(e)

# product along columns
torch.prod(e, dim=0)

# product along rows
torch.prod(e, dim=1)

tensor([0., 0.], dtype=torch.float64)

In [ ]:
# standard deveiation
torch.std(e)

# standard deveiation along columns
torch.std(e, dim=0)

# standard deveiation along rows
torch.std(e, dim=1)

tensor([4.9329, 4.9329], dtype=torch.float64)

In [ ]:
# variance
torch.var(e)

# variance along columns
torch.var(e, dim=0)

# variance along rows
torch.var(e, dim=1)

tensor([24.3333, 24.3333], dtype=torch.float64)

In [ ]:
# argmax
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

#### 4. Matrix Operations

In [ ]:
f = torch.randint(size=(2,3), low = 0, high = 10)
g = torch.randint(size=(2,3), low = 0, high = 10)

print(f)
print(g)

tensor([[7, 0, 0],
        [9, 5, 7]])
tensor([[3, 9, 4],
        [0, 5, 7]])


In [ ]:
# matrix multiplication
torch.matmul(f, g.T)

tensor([[ 21,   0],
        [100,  74]])

In [ ]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])

In [ ]:
# dot product
torch.dot(v1, v2)

tensor(11)

In [ ]:
# transpose
torch.transpose(g, 0, 1)

tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [ ]:
h = torch.randint(size=(3,3), low = 0, high = 10, dtype=float)
h

tensor([[5., 9., 9.],
        [7., 5., 9.],
        [8., 9., 7.]], dtype=torch.float64)

In [ ]:
# determinant
torch.det(h)

tensor(184., dtype=torch.float64)

In [ ]:
# inverese
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]], dtype=torch.float64)

#### 5. Comparision Operators

In [ ]:
i = torch.randint(size=(2,3), low = 0, high = 10)
j = torch.randint(size=(2,3), low = 0, high = 10)

print(i)
print(j)

tensor([[9, 2, 6],
        [7, 7, 8]])
tensor([[3, 6, 1],
        [5, 5, 0]])


In [ ]:
# greater than
i > j

# lesser than
i < j

# equal to
i == j

# not equal to
i != j

# greater than or equal to
i >= j

# lesser than or equal to
i <= j

tensor([[False,  True, False],
        [False, False, False]])

#### 6. Special Functions

In [ ]:
k = torch.randint(size=(2,3), low = 0, high = 10, dtype=float)
k

tensor([[4., 3., 8.],
        [8., 3., 3.]], dtype=torch.float64)

In [ ]:
# log
torch.log(k)

# exp
torch.exp(k)

# sin
torch.sin(k)

# cos
torch.cos(k)

# tan
torch.tan(k)

# sigmoid
torch.sigmoid(k)

# sqrt
torch.sqrt(k)

# relu
torch.relu(k)

# softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.5000, 0.9933],
        [0.9820, 0.5000, 0.0067]], dtype=torch.float64)

### Inpolace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])
tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])


In [ ]:
m.add_(n)

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
m.relu_()

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

### Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b = a
b

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
a[0][0] = 0
print(a)
print(b)

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])
tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


In [ ]:
# memory address
print(id(a))
print(id(b))

134464925082608
134464925082608


In [ ]:
c = torch.rand(2,3)
c

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
d = c.clone()
b

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
c[0][0] = 0
print(c)
print(d)

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])
tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])


In [ ]:
# memory address
print(id(c))
print(id(d))

134464925088048
134464925089248


### Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
# creating a Tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
b = a.to(device)

In [ ]:
b + 5

tensor([[5.0497, 5.1780, 5.3011],
        [5.1893, 5.9186, 5.2131]], device='cuda:0')

#### Comparision " CPU vs GPU "

In [ ]:
import torch
import time

size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()

cpu_time = end_time - start_time

print(f"Time taken on CPU : {cpu_time:.4f} seconds")

Time taken on CPU : 16.7569 seconds


In [ ]:
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
end_time = time.time()

gpu_time = end_time - start_time

print(f"Time taken on GPU : {gpu_time:.4f} seconds")

Time taken on GPU : 0.1197 seconds


In [ ]:
print("Speed up : ", cpu_time / gpu_time)

Speed up :  140.01033887196732


### Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.9514, 0.0141, 0.8903, 0.1649],
         [0.3162, 0.1331, 0.6763, 0.4254],
         [0.2375, 0.5430, 0.1174, 0.6532]],

        [[0.5115, 0.3094, 0.7907, 0.7351],
         [0.2693, 0.8009, 0.5839, 0.0061],
         [0.4671, 0.8243, 0.2861, 0.7459]]])

In [ ]:
# permute
b.permute(2,0,1)

tensor([[[0.9514, 0.3162, 0.2375],
         [0.5115, 0.2693, 0.4671]],

        [[0.0141, 0.1331, 0.5430],
         [0.3094, 0.8009, 0.8243]],

        [[0.8903, 0.6763, 0.1174],
         [0.7907, 0.5839, 0.2861]],

        [[0.1649, 0.4254, 0.6532],
         [0.7351, 0.0061, 0.7459]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
c = torch.rand(228,228,3)
c.unsqueeze(0).shape

torch.Size([1, 228, 228, 3])

In [ ]:
# squeeze
d = torch.rand(1,228,228,3)
d.squeeze(0).shape

torch.Size([228, 228, 3])

### Numpy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])